import { describe, expect, it } from 'vitest';
import { blankProject, connect, demoProject, junction, newColumn, newTable, sqlExport, validateProject } from './schema';
describe('schema invariants',()=>{
  it('round-trips a diagram with positions, keys, and relationships',()=>{const p=demoProject();expect(validateProject(JSON.parse(JSON.stringify(p)))).toEqual(p);});
  it('rejects case-insensitive duplicate names and dangling references',()=>{const p=demoProject();p.tables[1].name=p.tables[0].name.toUpperCase();expect(()=>validateProject(p)).toThrow('sudah digunakan');const other=demoProject();other.tables.shift();expect(()=>validateProject(other)).toThrow('Endpoint');});
  it('rejects mismatched foreign-key types and a second reference to the same FK',()=>{const p=demoProject();p.tables[1].columns[1].type='uuid';expect(()=>validateProject(p)).toThrow('Tipe data');const q=demoProject(),r=q.relations[0];expect(()=>connect(q,r.fromTable,r.fromColumn,r.toTable,r.toColumn,r.kind)).toThrow('sudah memiliki');});
  it('makes the target of a one-to-one unique',()=>{const p=blankProject(),a=newTable('a'),b=newTable('b');b.columns.push(newColumn('a_id'));p.tables=[a,b];const q=connect(p,a.id,a.columns[0].id,b.id,b.columns[1].id,'one-to-one');expect(q.tables[1].columns[1].unique).toBe(true);expect(p.tables[1].columns[1].unique).toBe(false);});
  it('creates a physical many-to-many junction with a composite primary key',()=>{const p=demoProject();const q=junction(p,p.tables[0],p.tables[3]);const last=q.tables.at(-1)!;expect(last.columns).toHaveLength(2);expect(last.columns.every(c=>c.primaryKey&&!c.nullable)).toBe(true);expect(q.relations).toHaveLength(p.relations.length+2);expect(sqlExport(q)).toContain('PRIMARY KEY ("customers_id", "products_id")');});
  it('does not allow referencing part of a composite key without UNIQUE',()=>{const p=demoProject();p.tables[0].columns[1].primaryKey=true;p.tables[0].columns[1].nullable=false;expect(()=>validateProject(p)).toThrow('PK tunggal');});
  it('rejects unsupported versions and nonfinite coordinates',()=>{const p=demoProject();expect(()=>validateProject({...p,version:2})).toThrow();p.tables[0].x=Infinity;expect(()=>validateProject(p)).toThrow();});
});
describe('SQL export',()=>{
  it.each(['postgres','mysql','sqlserver'] as const)('exports %s using dialect-specific types and separate FK statements',dialect=>{const p=demoProject();p.dialect=dialect;p.tables[0].columns.push(newColumn('metadata','json'));p.tables[0].columns.push(newColumn('external_id','uuid'));const sql=sqlExport(p);expect(sql.match(/CREATE TABLE /g)).toHaveLength(5);expect(sql.match(/ALTER TABLE /g)).toHaveLength(4);if(dialect==='sqlserver'){expect(sql).toContain('DATETIME2');expect(sql).toContain('UNIQUEIDENTIFIER');expect(sql).toContain('NVARCHAR(MAX)');}if(dialect==='mysql')expect(sql).toContain('`customers`');});
  it('quotes string defaults, validates numeric defaults, and handles booleans',()=>{const p=demoProject();p.tables[0].columns[1].defaultValue="O'Reilly";expect(sqlExport(p)).toContain("DEFAULT 'O''Reilly'");p.tables[0].columns[0].defaultValue='1; DROP TABLE customers';expect(()=>sqlExport(p)).toThrow('harus angka');});
});
