import { Column, Project, Table, blankProject, connect, newColumn, newTable, uid, validateProject } from './schema';

export type SqlImportResult = { project: Project; warnings: string[] };
const typeFor=(raw:string): Column['type']=>{const type=raw.toLowerCase().replace(/\s+/g,' ');if(/\buuid\b/.test(type))return'uuid';if(/\bbigint\b|\bbigserial\b/.test(type))return'bigint';if(/\bint\b|\bserial\b/.test(type))return'int';if(/\bbool/.test(type))return'boolean';if(/\bjson/.test(type))return'json';if(/\bdate\b/.test(type)&&!/timestamp|datetime/.test(type))return'date';if(/timestamp|datetime/.test(type))return'timestamp';if(/decimal|numeric|money/.test(type)){const decimal=type.match(/(?:decimal|numeric)\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/);const candidate=decimal?`decimal(${decimal[1]},${decimal[2]})`: 'decimal(19,4)';return (['decimal(18,2)','decimal(19,4)','decimal(24,8)','decimal(38,18)'] as string[]).includes(candidate)?candidate as Column['type']:'decimal(19,4)';}if(/\btext\b/.test(type))return'text';if(/char\s*\(\s*3\s*\)/.test(type))return'varchar(3)';return'varchar(255)';};
function uncomment(sql:string){let out='',quote='';for(let i=0;i<sql.length;i++){const c=sql[i],next=sql[i+1];if(quote){out+=c;if(c===quote&&sql[i-1]!=='\\')quote='';continue;}if(c==='\''||c==='"'||c==='`'){quote=c;out+=c;continue;}if(c==='-'&&next==='-'){while(i<sql.length&&sql[i]!=='\n')i++;out+='\n';continue;}if(c==='/'&&next==='*'){i+=2;while(i<sql.length&&(sql[i]!=='*'||sql[i+1]!=='/'))i++;i++;continue;}out+=c;}return out;}
function splitTop(value:string,delimiter=','){const parts:string[]=[];let start=0,depth=0,quote='';for(let i=0;i<value.length;i++){const c=value[i];if(quote){if(c===quote&&value[i-1]!=='\\')quote='';continue;}if(c==='\''||c==='"'||c==='`'){quote=c;continue;}if(c==='(')depth++;else if(c===')')depth--;else if(c===delimiter&&depth===0){parts.push(value.slice(start,i));start=i+1;}}parts.push(value.slice(start));return parts.map(x=>x.trim()).filter(Boolean);}
const nameOf=(value:string)=>value.trim().split('.').at(-1)!.replace(/^[`"\[]|[`"\]]$/g,'');
export function importSql(sql:string):SqlImportResult {const warnings:string[]=[];const project=blankProject();project.name='Schema import';const foreign:{table:Table;column:string;targetTable:string;targetColumn:string}[]=[];const clean=uncomment(sql);const creates=[...clean.matchAll(/create\s+table\s+(?:if\s+not\s+exists\s+)?([\w`"\[\].]+)\s*\(([\s\S]*?)\)\s*(?:;|$)/gi)];
  for(let order=0;order<creates.length;order++){const [,rawName,body]=creates[order],name=nameOf(rawName);if(!/^[A-Za-z_][A-Za-z0-9_]{0,62}$/.test(name)){warnings.push(`Tabel ${rawName} dilewati: nama tidak didukung.`);continue;}const table=newTable(name,100+(order%4)*340,100+Math.floor(order/4)*330);table.columns=[];const primary=new Set<string>(),unique=new Set<string>();
    for(const part of splitTop(body)){const pk=part.match(/^primary\s+key\s*\(([^)]+)\)/i);if(pk){splitTop(pk[1]).forEach(x=>primary.add(nameOf(x).toLowerCase()));continue;}const uq=part.match(/^(?:constraint\s+[\w`"\[\]]+\s+)?unique\s*\(([^)]+)\)/i);if(uq){splitTop(uq[1]).forEach(x=>unique.add(nameOf(x).toLowerCase()));continue;}if(/^(?:constraint\s+)?(?:foreign\s+key|check|unique|primary\s+key)/i.test(part))continue;const match=part.match(/^([`"\[\]\w]+)\s+(.+)$/s);if(!match)continue;const columnName=nameOf(match[1]),definition=match[2],column=newColumn(columnName,typeFor(definition));column.nullable=!/not\s+null|primary\s+key/i.test(definition);column.primaryKey=/primary\s+key/i.test(definition);column.unique=/\bunique\b/i.test(definition);const defaultMatch=definition.match(/\bdefault\s+(.+?)(?:\s+(?:not\s+null|unique|primary\s+key|references)\b|$)/i);if(defaultMatch)column.defaultValue=defaultMatch[1].trim();table.columns.push(column);const reference=definition.match(/references\s+([\w`"\[\].]+)\s*\(([^)]+)\)/i);if(reference)foreign.push({table,column:columnName,targetTable:nameOf(reference[1]),targetColumn:nameOf(reference[2])});}
    if(!table.columns.length){warnings.push(`Tabel ${name} dilewati: tidak ada kolom yang terbaca.`);continue;}for(const c of table.columns){if(primary.has(c.name.toLowerCase())){c.primaryKey=true;c.nullable=false;}if(unique.has(c.name.toLowerCase()))c.unique=true;}project.tables.push(table);
  }
  for(const statement of splitTop(clean,';')){const match=statement.match(/(?:alter\s+table\s+)?([\w`"\[\].]+).*?foreign\s+key\s*\(([^)]+)\)\s*references\s+([\w`"\[\].]+)\s*\(([^)]+)\)/is);if(match){const table=project.tables.find(t=>t.name.toLowerCase()===nameOf(match[1]).toLowerCase());if(table)foreign.push({table,column:nameOf(match[2]),targetTable:nameOf(match[3]),targetColumn:nameOf(match[4])});}}
  for(const fk of foreign){const source=fk.table.columns.find(c=>c.name.toLowerCase()===fk.column.toLowerCase()),target=project.tables.find(t=>t.name.toLowerCase()===fk.targetTable.toLowerCase()),targetColumn=target?.columns.find(c=>c.name.toLowerCase()===fk.targetColumn.toLowerCase());if(!source||!target||!targetColumn){warnings.push(`Relasi ${fk.table.name}.${fk.column} dilewati: referensi tidak ditemukan.`);continue;}if(source.type!==targetColumn.type){warnings.push(`Relasi ${fk.table.name}.${fk.column} dilewati: tipe data berbeda.`);continue;}if(!targetColumn.primaryKey&&!targetColumn.unique){targetColumn.unique=true;}try{const next=connect(project,target.id,targetColumn.id,fk.table.id,source.id,'one-to-many');project.tables=next.tables;project.relations=next.relations;}catch(error){warnings.push((error as Error).message);}}
  if(!project.tables.length)throw new Error('Tidak menemukan perintah CREATE TABLE yang didukung.');project.id=uid();return {project:validateProject(project),warnings};
}
