'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Database, Plus, Search, ChevronDown, ChevronRight, FolderOpen, ArrowUpRight, Download, Upload, Undo2, Redo2, Sun, Moon, Check, GitBranch, Table2, X, Trash2, Pencil, Save, LayoutGrid, HelpCircle, FileCode2, Copy, LoaderCircle, AlertCircle, CircleHelp } from 'lucide-react';
import Diagram from './Diagram';
import TableDialog from './TableDialog';
import RelationDialog from './RelationDialog';
import { blankProject, COLORS, demoProject, newTable, Project, ProjectInfo, Relation, sqlExport, Table, uid, validateProject } from '../lib/schema';
import { importSql } from '../lib/sql-import';

type Selection = {type:'table'|'relation';id:string}|null;
type Confirm = {title:string;message:string;actionLabel?:string;action:()=>void|Promise<void>};
async function api<T>(path:string,options?:RequestInit):Promise<T> {
  const response=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...options?.headers},signal:AbortSignal.timeout(15000)});
  if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error||`Server tidak tersedia (${response.status}).`);}
  return response.status===204?undefined as T:response.json();
}
const fingerprint=(p:Project)=>JSON.stringify({...p,revision:0,updatedAt:undefined});
export default function Editor(){
  const [project,setProject]=useState<Project|null>(null); const current=useRef<Project|null>(null);
  const [selection,setSelection]=useState<Selection>(null); const [status,setStatus]=useState('Memuat project…');
  const [failure,setFailure]=useState(''); const [notice,setNotice]=useState(''); const [dark,setDark]=useState(false);
  const [query,setQuery]=useState(''); const [tab,setTab]=useState<'tables'|'relations'>('tables');
  const [tableDraft,setTableDraft]=useState<Table|null>(null); const [relationOpen,setRelationOpen]=useState(false);
  const [relationInitial,setRelationInitial]=useState<Partial<Pick<Relation,'id'|'fromTable'|'fromColumn'|'toTable'|'toColumn'|'kind'|'joinedColumns'|'showForeignKey'>>|undefined>();
  const [projectsOpen,setProjectsOpen]=useState(false); const [projects,setProjects]=useState<ProjectInfo[]>([]);
  const [exportOpen,setExportOpen]=useState(false); const [helpOpen,setHelpOpen]=useState(false); const [confirm,setConfirm]=useState<Confirm|null>(null);
  const [fitSignal,setFitSignal]=useState(0); const [history,setHistory]=useState<{past:Project[];future:Project[]}>({past:[],future:[]});
  const revision=useRef(new Map<string,number>()); const saved=useRef(new Map<string,string>()); const queue=useRef<Promise<boolean>>(Promise.resolve(true));
  const fileInput=useRef<HTMLInputElement>(null); const [busy,setBusy]=useState(false);
  const install=useCallback((p:Project,isSaved=false)=>{current.current=p;setProject(p);revision.current.set(p.id,p.revision);if(isSaved)saved.current.set(p.id,fingerprint(p));setSelection(null);setHistory({past:[],future:[]});setStatus(isSaved?'Semua perubahan tersimpan':'Belum tersimpan');setFailure('');},[]);
  const load=useCallback(async()=>{try{const list=await api<ProjectInfo[]>('/projects');setProjects(list);if(list.length){const latest=[...list].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))[0];install(validateProject(await api(`/projects/${latest.id}`)),true);}else{install(demoProject());setTimeout(()=>setFitSignal(x=>x+1),100);}}catch(e){setFailure((e as Error).message);}},[install]);
  // Initial state is populated only after the asynchronous API response.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
  const saveProject=useCallback((snapshot:Project):Promise<boolean>=>{
    const task=queue.current.then(async()=>{
      const signature=fingerprint(snapshot);if(saved.current.get(snapshot.id)===signature){if(current.current?.id===snapshot.id&&fingerprint(current.current)===signature)setStatus('Semua perubahan tersimpan');return true;}
      if(current.current?.id===snapshot.id)setStatus('Menyimpan…');
      try{
        const result=await api<Project>(`/projects/${snapshot.id}`,{method:'PUT',body:JSON.stringify({...snapshot,revision:revision.current.get(snapshot.id)??snapshot.revision})});
        revision.current.set(snapshot.id,result.revision);saved.current.set(snapshot.id,signature);
        if(current.current?.id===snapshot.id){setFailure('');setStatus(fingerprint(current.current)===signature?'Semua perubahan tersimpan':'Perubahan belum tersimpan');}return true;
      }catch(e){saved.current.delete(snapshot.id);if(current.current?.id===snapshot.id){setFailure((e as Error).message);setStatus('Gagal menyimpan');}return false;}
    });queue.current=task;return task;
  },[]);
  useEffect(()=>{if(!project)return;const timer=setTimeout(()=>{void saveProject(project);},900);return()=>clearTimeout(timer);},[project,saveProject]);
  useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(current.current&&saved.current.get(current.current.id)!==fingerprint(current.current)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t);},[notice]);
  const modalKey=confirm?'confirm':tableDraft?'table':relationOpen?'relation':projectsOpen?'projects':exportOpen?'export':helpOpen?'help':'';
  useEffect(()=>{
    if(!modalKey)return;
    const previous=document.activeElement as HTMLElement|null;
    const dialogs=document.querySelectorAll<HTMLElement>('[role="dialog"],[role="alertdialog"]');const dialog=dialogs[dialogs.length-1];if(!dialog)return;
    const focusable=()=>Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]'));
    const preferred=dialog.querySelector<HTMLElement>('input:not([disabled]),select:not([disabled]),textarea:not([disabled])')||focusable()[0];preferred?.focus();
    const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=focusable();const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};
    document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus();};
  },[modalKey]);
  const commit=useCallback((next:Project,withHistory=true)=>{const old=current.current;if(!old)return;try{validateProject(next);if(withHistory)setHistory(h=>({past:[...h.past,old].slice(-80),future:[]}));current.current=next;setProject(next);setStatus('Perubahan belum tersimpan');}catch(e){setNotice((e as Error).message);}},[]);
  function undo(){if(!project||!history.past.length)return;const prev=history.past.at(-1)!;setHistory({past:history.past.slice(0,-1),future:[project,...history.future]});current.current=prev;setProject(prev);setSelection(null);setStatus('Perubahan belum tersimpan');}
  function redo(){if(!project||!history.future.length)return;const next=history.future[0];setHistory({past:[...history.past,project],future:history.future.slice(1)});current.current=next;setProject(next);setSelection(null);setStatus('Perubahan belum tersimpan');}
  function download(text:string,filename:string,mime='application/json'){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function deleteSelection(){if(!project||!selection)return;const s=selection;if(s.type==='table'){const t=project.tables.find(t=>t.id===s.id);if(!t)return;const n=project.relations.filter(r=>r.fromTable===s.id||r.toTable===s.id).length;setConfirm({title:`Hapus tabel ${t.name}?`,message:`Tabel beserta ${n} relasi terkait akan dihapus. Anda dapat mengembalikannya dengan Undo.`,action:()=>{commit({...project,tables:project.tables.filter(t=>t.id!==s.id),relations:project.relations.filter(r=>r.fromTable!==s.id&&r.toTable!==s.id)});setSelection(null);}});}else{commit({...project,relations:project.relations.filter(r=>r.id!==s.id)});setSelection(null);}}
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(tableDraft||relationOpen||projectsOpen||exportOpen||helpOpen||confirm)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(project)void saveProject(project);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if(e.key==='Delete')deleteSelection();if(e.key==='Escape')setSelection(null);};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);});
  async function showProjects(){try{setProjectsOpen(true);setProjects(await api<ProjectInfo[]>('/projects'));}catch(e){setNotice((e as Error).message);}}
  async function switchProject(id:string){if(!project||busy)return;setBusy(true);try{if(!await saveProject(project))return;install(validateProject(await api(`/projects/${id}`)),true);setProjectsOpen(false);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function createProject(){if(busy)return;setBusy(true);try{if(project&&!await saveProject(project))return;install(blankProject());setProjectsOpen(false);}finally{setBusy(false);}}
  async function importFile(file:File){try{if(file.size>4*1024*1024)throw new Error('File import maksimal 4 MB.');const content=await file.text();const result=file.name.toLowerCase().endsWith('.sql')?importSql(content):{project:validateProject(JSON.parse(content)),warnings:[]};if(project&&!await saveProject(project))return;const p=result.project;install({...p,id:uid(),revision:0,name:`${p.name.slice(0,100)} (import)`});setFitSignal(x=>x+1);setNotice(result.warnings.length?`Schema diimpor. ${result.warnings.length} bagian dilewati: ${result.warnings[0]}`:'Schema diimpor sebagai project baru.');}catch(e){setNotice((e as Error).message);}finally{if(fileInput.current)fileInput.current.value='';}}
  function addTable(){if(!project)return;let n=project.tables.length+1;while(project.tables.some(t=>t.name===`table_${n}`))n++;setTableDraft(newTable(`table_${n}`,Math.round((180-project.viewport.x)/project.viewport.zoom/20)*20,Math.round((140-project.viewport.y)/project.viewport.zoom/20)*20,COLORS[project.tables.length%COLORS.length]));}
  const activeTable=project?.tables.find(t=>selection?.type==='table'&&t.id===selection.id);
  const activeRelation=project?.relations.find(r=>selection?.type==='relation'&&r.id===selection.id);
  let sql='',sqlError='';if(project&&exportOpen){try{sql=sqlExport(project);}catch(e){sqlError=(e as Error).message;}}
  if(!project)return <main className="loading-screen"><Database size={38}/><h1>Schema Studio</h1>{failure?<><p role="alert">{failure}</p><button className="primary" onClick={()=>void load()}>Coba hubungkan kembali</button></>:<p>Menyiapkan workspace…</p>}</main>;
  return <main className={`studio ${dark?'dark':''}`}>
    <header className="app-header workspace-header"><div className="brand"><span className="brand-mark"><Database size={22}/></span><span>schema<span className="brand-light">studio</span><small>VISUAL DATABASE DESIGNER</small></span></div><div className="header-divider"/><button className="workspace-switch" onClick={()=>void showProjects()}><FolderOpen size={15}/> My workspace <ChevronDown size={13}/></button><div className="header-divider project-divider"/><div className="project-title"><span className="project-icon"><GitBranch size={21}/></span><div><input aria-label="Nama project header" maxLength={120} value={project.name} onChange={e=>{if(e.target.value.trim())commit({...project,name:e.target.value});}}/></div><span className="version-pill">DRAFT</span></div><div className="header-spacer"/><span className="save-status" role="status">{status}</span><div className="project-actions"><button className="icon-button" title="Undo (Ctrl+Z)" aria-label="Undo header" disabled={!history.past.length} onClick={undo}><Undo2 size={17}/></button><button className="icon-button" title="Redo (Ctrl+Y)" aria-label="Redo header" disabled={!history.future.length} onClick={redo}><Redo2 size={17}/></button><button onClick={()=>fileInput.current?.click()}><Upload size={15}/> Import</button><button aria-label="Simpan header" onClick={()=>void saveProject(project)} title="Ctrl+S"><Save size={15}/><span className="optional-text">Simpan</span></button><button className="primary" onClick={()=>setExportOpen(true)}><Download size={15}/> Export</button></div><span className="local-tag"><span className="live-dot"/> Local</span><button className="icon-button" aria-label="Ganti tema" title="Ganti tema" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" aria-label="Bantuan" onClick={()=>setHelpOpen(true)}><HelpCircle size={18}/></button><span className="avatar">ME</span></header>
    <div className="project-bar"><div className="project-title"><span className="project-icon"><GitBranch size={21}/></span><div><input aria-label="Nama project" maxLength={120} value={project.name} onChange={e=>{if(e.target.value.trim())commit({...project,name:e.target.value});}}/><div className="save-status" role="status">{status==='Menyimpan…'?<LoaderCircle size={12} className="spin"/>:failure?<AlertCircle size={12}/>:<Check size={12}/>} {status}</div></div><span className="version-pill">DRAFT</span></div><div className="project-actions"><button className="icon-button" title="Undo (Ctrl+Z)" aria-label="Undo" disabled={!history.past.length} onClick={undo}><Undo2 size={17}/></button><button className="icon-button" title="Redo (Ctrl+Y)" aria-label="Redo" disabled={!history.future.length} onClick={redo}><Redo2 size={17}/></button><span className="separator"/><button onClick={()=>fileInput.current?.click()}><Upload size={15}/> Import</button><button onClick={()=>void saveProject(project)} title="Ctrl+S"><Save size={15}/><span className="optional-text">Simpan</span></button><button className="primary" onClick={()=>setExportOpen(true)}><Download size={15}/> Export schema <ChevronDown size={13}/></button></div></div>
    {failure&&<div className="connection-error" role="alert"><AlertCircle size={15}/>{failure} Perubahan tetap ada di editor; export JSON untuk backup.<button onClick={()=>void saveProject(project)}>Coba simpan</button><button onClick={()=>setConfirm({title:'Muat ulang dari server?',actionLabel:'Muat ulang',message:'Perubahan lokal yang belum tersimpan akan diganti. Export JSON terlebih dahulu jika ingin menyimpannya.',action:async()=>{try{await queue.current;install(validateProject(await api(`/projects/${project.id}`)),true);}catch(e){setNotice((e as Error).message);}}})}>Muat ulang</button></div>}
    <div className="workspace-body"><aside className="sidebar"><div className="sidebar-heading"><span>EXPLORER</span><button className="icon-button" aria-label="Buka project" title="Buka project" onClick={()=>void showProjects()}><FolderOpen size={16}/></button></div><div className="search-field"><Search size={15}/><input aria-label="Cari tabel" placeholder="Cari tabel…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></div><div className="sidebar-tabs"><button className={tab==='tables'?'active':''} onClick={()=>setTab('tables')}>Tabel <span>{project.tables.length}</span></button><button className={tab==='relations'?'active':''} onClick={()=>setTab('relations')}>Relasi <span>{project.relations.length}</span></button></div>
      <div className="explorer-list">{tab==='tables'?<><div className="schema-group"><ChevronDown size={12}/><Database size={13}/> public <span>{project.tables.length}</span></div>{project.tables.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())).map(t=><div key={t.id} className={`explorer-table ${selection?.id===t.id?'active':''}`}><button onClick={()=>{setSelection({type:'table',id:t.id});commit({...project,viewport:{...project.viewport,x:80-t.x*project.viewport.zoom,y:100-t.y*project.viewport.zoom}},false);}}><ChevronRight size={13}/><Table2 size={15} style={{color:t.color}}/><span>{t.name}</span><small>{t.columns.length}</small></button>{selection?.id===t.id&&<div className="explorer-columns">{t.columns.map(c=><span key={c.id}><span>{c.primaryKey?'◆':'·'}</span>{c.name}<small>{c.type}</small></span>)}</div>}</div>)}{!project.tables.length&&<p className="sidebar-empty">Belum ada tabel. Mulai dengan menambahkan tabel baru.</p>}<button className="sidebar-add" onClick={addTable}><Plus size={15}/> Tambah tabel</button></>:<>{project.relations.map(r=><button className={`relation-list-item ${selection?.id===r.id?'active':''}`} key={r.id} onClick={()=>setSelection({type:'relation',id:r.id})}><GitBranch size={16}/><span>{project.tables.find(t=>t.id===r.fromTable)?.name}<small>→ {project.tables.find(t=>t.id===r.toTable)?.name}</small></span><em>{r.kind==='one-to-one'?'1:1':'1:N'}</em></button>)}{!project.relations.length&&<p className="sidebar-empty">Tarik titik kolom untuk menghubungkan tabel.</p>}</>}</div>
      <div className="sidebar-bottom"><div className="tip-icon"><CircleHelp size={17}/></div><strong>Hubungkan ide, bukan sintaks.</strong><p>Tarik titik pada kolom PK ke kolom FK untuk membuat relasi.</p><button onClick={()=>setHelpOpen(true)}>Panduan singkat <ArrowUpRight size={14}/></button></div>
    </aside><section className="diagram-area"><div className="diagram-toolbar"><div className="diagram-tab"><LayoutGrid size={15}/> Diagram <span className="tab-dot"/></div><div className="toolbar-actions"><label className="dialect-select"><Database size={13}/><select aria-label="Database dialect" value={project.dialect} onChange={e=>commit({...project,dialect:e.target.value as Project['dialect']})}><option value="postgres">PostgreSQL</option><option value="mysql">MySQL</option><option value="sqlserver">SQL Server</option></select></label><span className="separator"/><button onClick={()=>{setRelationInitial(undefined);setRelationOpen(true);}} disabled={!project.tables.length}><GitBranch size={15}/> Tambah relasi</button><button className="soft-primary" disabled={project.tables.length>=200} onClick={addTable}><Plus size={16}/> Tambah tabel</button></div></div>
      <Diagram project={project} selection={selection} onSelect={setSelection} onEdit={setTableDraft} onAdd={addTable} onMove={(id,x,y)=>commit({...project,tables:project.tables.map(t=>t.id===id?{...t,x,y}:t)})} onView={viewport=>commit({...project,viewport},false)} onSnap={()=>commit({...project,snap:!project.snap},false)} fitSignal={fitSignal} onConnect={(fromTable,fromColumn,toTable,toColumn)=>{if(fromColumn===toColumn)return;setRelationInitial({fromTable,fromColumn,toTable,toColumn});setRelationOpen(true);}}/>
    </section>{(activeTable||activeRelation)&&<aside className="properties"><div className="sidebar-heading"><span>PROPERTIES</span><button className="icon-button" aria-label="Tutup properti" onClick={()=>setSelection(null)}><X size={16}/></button></div>{activeTable?<><div className="property-title"><Table2 size={22} style={{color:activeTable.color}}/><h3>{activeTable.name}</h3><span>TABLE</span></div><label>Schema<input value="public" readOnly/></label><label>Kolom<input value={`${activeTable.columns.length} columns`} readOnly/></label><label>Catatan<p className="property-note">{activeTable.note||'Belum ada catatan untuk tabel ini.'}</p></label><button className="wide" onClick={()=>setTableDraft(activeTable)}><Pencil size={15}/> Edit tabel & kolom</button><div className="property-section"><h4>Relasi terkait</h4>{project.relations.filter(r=>r.fromTable===activeTable.id||r.toTable===activeTable.id).map(r=><button key={r.id} className="property-relation" onClick={()=>setSelection({type:'relation',id:r.id})}><GitBranch size={14}/>{project.tables.find(t=>t.id===(r.fromTable===activeTable.id?r.toTable:r.fromTable))?.name}<ChevronRight size={12}/></button>)}</div></>:activeRelation?<><div className="property-title"><GitBranch size={22}/><h3>Foreign key</h3><span>{activeRelation.kind==='one-to-one'?'1 : 1':'1 : N'}</span></div><label>Referensi<p className="property-note mono">{project.tables.find(t=>t.id===activeRelation.fromTable)?.name}.{project.tables.flatMap(t=>t.columns).find(c=>c.id===activeRelation.fromColumn)?.name}</p></label><label>Foreign key<p className="property-note mono">{project.tables.find(t=>t.id===activeRelation.toTable)?.name}.{project.tables.flatMap(t=>t.columns).find(c=>c.id===activeRelation.toColumn)?.name}</p></label><p className="form-hint">Hapus dan buat ulang relasi untuk mengganti endpoint atau cardinality.</p></>:null}<button className="danger wide delete-property" onClick={deleteSelection}><Trash2 size={15}/> Hapus {activeTable?'tabel':'relasi'}</button></aside>}</div>
    <footer className="statusbar"><span><span className="live-dot"/> {failure?'Perlu disimpan ulang':'Workspace siap'}</span><span>{project.tables.length} tabel<span className="status-sep">/</span>{project.tables.reduce((n,t)=>n+t.columns.length,0)} kolom<span className="status-sep">/</span>{project.relations.length} relasi</span><div/><span>Snap to grid <strong>{project.snap?'ON':'OFF'}</strong></span><span className="status-sep">|</span><span>Schema Studio <span className="muted">v1.0</span></span></footer>
    <input type="file" accept=".json,.sql,application/json,text/sql" hidden ref={fileInput} onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);}}/>
    {tableDraft&&<TableDialog key={tableDraft.id} table={tableDraft} project={project} onClose={()=>setTableDraft(null)} onSave={t=>{commit({...project,tables:project.tables.some(x=>x.id===t.id)?project.tables.map(x=>x.id===t.id?t:x):[...project.tables,t]});setTableDraft(null);setSelection({type:'table',id:t.id});}}/>}
    {relationOpen&&<RelationDialog project={project} initial={relationInitial} onClose={()=>setRelationOpen(false)} onSave={p=>{commit(p);setRelationOpen(false);setNotice('Relasi berhasil dibuat.');}}/>}
    {projectsOpen&&<div className="modal-backdrop"><section className="modal projects-modal" role="dialog" aria-modal="true" aria-label="Daftar project"><header className="modal-header"><div><span className="eyebrow">MY WORKSPACE</span><h2>Project schema</h2></div><button className="icon-button" aria-label="Tutup project" onClick={()=>setProjectsOpen(false)}><X size={20}/></button></header><div className="modal-body"><button className="primary wide" disabled={busy} onClick={()=>void createProject()}><Plus size={16}/> Project baru</button><div className="project-list">{projects.length===0&&<p>Belum ada project tersimpan.</p>}{projects.map(p=><div key={p.id}><button disabled={busy} onClick={()=>void switchProject(p.id)}><span className="project-icon"><Database size={20}/></span><span><strong>{p.name}</strong><small>{p.tableCount} tabel · {p.updatedAt?new Date(p.updatedAt).toLocaleString('id-ID'):''}</small></span>{p.id===project.id&&<span className="version-pill">AKTIF</span>}</button><button className="icon-button danger" disabled={busy||p.id===project.id} aria-label={`Hapus project ${p.name}`} title={p.id===project.id?'Buka project lain sebelum menghapus':'Hapus project'} onClick={()=>setConfirm({title:`Hapus project ${p.name}?`,message:'Project dihapus dari daftar. File backup .deleted tetap disimpan di server.',action:async()=>{try{await api(`/projects/${p.id}?revision=${p.revision}`,{method:'DELETE'});setProjects(await api('/projects'));}catch(e){setNotice((e as Error).message);}}})}><Trash2 size={16}/></button></div>)}</div></div></section></div>}
    {exportOpen&&<div className="modal-backdrop"><section className="modal export-modal" role="dialog" aria-modal="true" aria-label="Export schema"><header className="modal-header"><div><span className="eyebrow">TAKE YOUR SCHEMA FURTHER</span><h2>Export schema</h2></div><button className="icon-button" aria-label="Tutup export" onClick={()=>setExportOpen(false)}><X size={20}/></button></header><div className="modal-body"><div className="export-heading"><span><FileCode2 size={17}/> SQL · {project.dialect}</span><button disabled={!!sqlError} onClick={async()=>{try{await navigator.clipboard.writeText(sql);setNotice('SQL disalin.');}catch{setNotice('Clipboard tidak tersedia. Gunakan download SQL.');}}}><Copy size={14}/> Salin</button></div>{sqlError?<div className="form-error">{sqlError}</div>:<pre className="sql-preview">{sql}</pre>}<p className="form-hint">JSON menyimpan seluruh diagram, termasuk posisi tabel. SQL berisi DDL dan tidak dieksekusi oleh aplikasi.</p></div><footer className="modal-footer"><button onClick={()=>download(JSON.stringify({...project,revision:revision.current.get(project.id)||0},null,2),'schema.json')}><Download size={15}/> Download JSON</button><button className="primary" disabled={!!sqlError} onClick={()=>download(sql,'schema.sql','text/plain')}><Download size={15}/> Download SQL</button></footer></section></div>}
    {helpOpen&&<div className="modal-backdrop"><section className="modal help-modal" role="dialog" aria-modal="true" aria-label="Panduan singkat"><header className="modal-header"><div><span className="eyebrow">A LITTLE GUIDANCE</span><h2>Dari ide ke diagram.</h2></div><button className="icon-button" aria-label="Tutup bantuan" onClick={()=>setHelpOpen(false)}><X size={20}/></button></header><div className="modal-body"><ol className="help-steps"><li><strong>Tambahkan tabel</strong><p>Klik Tambah tabel. Isi nama, kolom, tipe data, dan key melalui form.</p></li><li><strong>Susun diagram</strong><p>Drag header tabel. Drag area kosong untuk pan, scroll untuk zoom, atau gunakan Fit diagram.</p></li><li><strong>Hubungkan data</strong><p>Tarik titik di sisi kolom PK/UNIQUE ke titik kolom FK. Pilih cardinality pada dialog. Gunakan Tambah relasi untuk many-to-many.</p></li><li><strong>Simpan dan bawa hasilnya</strong><p>Autosave aktif setelah 900 ms. Export JSON untuk backup atau SQL untuk database pilihan Anda.</p></li></ol><div className="shortcut-row"><kbd>Ctrl Z</kbd> Undo <kbd>Ctrl Y</kbd> Redo <kbd>Ctrl S</kbd> Simpan <kbd>Del</kbd> Hapus</div></div></section></div>}
    {confirm&&<div className="modal-backdrop confirm-backdrop"><section className="modal confirm-modal" role="alertdialog" aria-modal="true" aria-label={confirm.title}><div className="modal-body"><AlertCircle size={28} className="danger"/><h2>{confirm.title}</h2><p>{confirm.message}</p></div><footer className="modal-footer"><button autoFocus onClick={()=>setConfirm(null)}>Batal</button><button className="danger-solid" onClick={()=>{void confirm.action();setConfirm(null);}}>{confirm.actionLabel||'Hapus'}</button></footer></section></div>}
    {notice&&<div className="toast" role="status">{notice}<button aria-label="Tutup notifikasi" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {activeRelation&&<button className="relation-edit-fab" onClick={()=>{setRelationInitial(activeRelation);setRelationOpen(true);}}><Pencil size={15}/> Edit relasi & hasil join</button>}
  </main>;
}
