'use client';
import { useMemo, useState } from 'react';
import { ArrowRight, X } from 'lucide-react';
import { connect, isReferenceKey, junction, Project, Relation, validateProject } from '../lib/schema';

type Initial = Pick<Relation, 'id'|'fromTable'|'fromColumn'|'toTable'|'toColumn'|'kind'|'joinedColumns'|'showForeignKey'>;
export default function RelationDialog({project,initial,onSave,onClose}: {project:Project;initial?:Partial<Initial>;onSave:(p:Project)=>void;onClose:()=>void}) {
  const editing=Boolean(initial?.id); const [fromTable,setFromTable]=useState(initial?.fromTable||project.tables[0]?.id||''); const [toTable,setToTable]=useState(initial?.toTable||project.tables[1]?.id||project.tables[0]?.id||'');
  const a=project.tables.find(t=>t.id===fromTable), b=project.tables.find(t=>t.id===toTable); const [fromColumn,setFromColumn]=useState(initial?.fromColumn||a?.columns.find(c=>isReferenceKey(a,c))?.id||''); const [toColumn,setToColumn]=useState(initial?.toColumn||b?.columns.find(c=>!c.primaryKey)?.id||b?.columns[0]?.id||'');
  const [targetName,setTargetName]=useState(b?.columns.find(c=>c.id===(initial?.toColumn||b?.columns.find(c=>!c.primaryKey)?.id))?.name||''); const [kind,setKind]=useState<Relation['kind']|'many-to-many'>(initial?.kind||'one-to-many'); const [joinedColumns,setJoinedColumns]=useState<string[]>(initial?.joinedColumns||[]); const [showForeignKey,setShowForeignKey]=useState(initial?.showForeignKey??true); const [error,setError]=useState('');
  const eligible=useMemo(()=>a?.columns.filter(c=>!b?.columns.some(target=>target.name.toLowerCase()===c.name.toLowerCase()))||[],[a,b]);
  const chooseTarget=(tableId:string,columnId?:string)=>{const table=project.tables.find(t=>t.id===tableId);const column=table?.columns.find(c=>c.id===(columnId||table?.columns.find(c=>!c.primaryKey)?.id||table?.columns[0]?.id));setToTable(tableId);setToColumn(column?.id||'');setTargetName(column?.name||'');setJoinedColumns([]);};
  function save(){try{if(!a||!b)throw new Error('Pilih kedua tabel.');if(kind==='many-to-many'){if(editing)throw new Error('Relasi many-to-many dibuat melalui tabel penghubung dan tidak dapat diubah menjadi jenis ini.');onSave(junction(project,a,b));return;}const next=structuredClone(project);const table=next.tables.find(t=>t.id===toTable),column=table?.columns.find(c=>c.id===toColumn);if(!table||!column)throw new Error('Kolom foreign key belum dipilih.');const name=targetName.trim();if(!name)throw new Error('Nama kolom foreign key wajib diisi.');column.name=name;if(editing){const relation=next.relations.find(r=>r.id===initial?.id);if(!relation)throw new Error('Relasi tidak ditemukan.');Object.assign(relation,{fromTable,fromColumn,toTable,toColumn,kind,joinedColumns,showForeignKey});if(kind==='one-to-one')column.unique=true;onSave(validateProject(next));}else onSave(connect(next,fromTable,fromColumn,toTable,toColumn,kind,{joinedColumns,showForeignKey}));}catch(e){setError((e as Error).message);}}
  return <div className="modal-backdrop"><section className="modal relation-modal" role="dialog" aria-modal="true" aria-labelledby="relation-title" onKeyDown={e=>{if(e.key==='Escape')onClose();}}><header className="modal-header"><div><span className="eyebrow">CONNECT YOUR DATA</span><h2 id="relation-title">{editing?'Edit relasi':'Tambah relasi'}</h2></div><button className="icon-button" aria-label="Tutup relasi" onClick={onClose}><X size={20}/></button></header><div className="modal-body">
    <label>Jenis relasi<select autoFocus aria-label="Jenis relasi" value={kind} disabled={editing} onChange={e=>setKind(e.target.value as typeof kind)}><option value="one-to-many">One-to-many · 1 : N</option><option value="one-to-one">One-to-one · 1 : 1</option>{!editing&&<option value="many-to-many">Many-to-many · N : N</option>}</select></label>
    <div className="relation-fields"><div><label>Tabel referensi (1)<select aria-label="Tabel referensi" value={fromTable} onChange={e=>{setFromTable(e.target.value);const table=project.tables.find(t=>t.id===e.target.value)!;setFromColumn(table.columns.find(c=>isReferenceKey(table,c))?.id||'');setJoinedColumns([]);}}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<label>Kolom sumber (PK / UNIQUE)<select aria-label="Kolom referensi" value={fromColumn} onChange={e=>setFromColumn(e.target.value)}><option value="">Pilih kolom</option>{a?.columns.filter(c=>isReferenceKey(a,c)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label>}</div><ArrowRight size={22}/><div><label>Tabel tujuan (FK)<select aria-label="Tabel tujuan" value={toTable} onChange={e=>chooseTarget(e.target.value)}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<><label>Kolom foreign key<select aria-label="Kolom tujuan" value={toColumn} onChange={e=>chooseTarget(toTable,e.target.value)}>{b?.columns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label><label className="relation-rename">Nama kolom di tabel tujuan<input aria-label="Nama baru kolom foreign key" value={targetName} maxLength={63} onChange={e=>setTargetName(e.target.value)} placeholder="contoh: toko"/><small>Nama boleh berbeda, misalnya <code>cabang</code> menjadi <code>toko</code>; relasi tetap menunjuk data yang sama.</small></label></>}</div></div>
    {kind!=='many-to-many'&&<section className="join-settings"><h3>Kolom hasil join</h3><p>Centang kolom tabel referensi yang ingin dimunculkan dari hasil join. Kolom bernama sama dengan tabel tujuan tidak tersedia agar tidak diduplikasi.</p><div className="join-columns">{eligible.map(c=><label key={c.id}><input type="checkbox" checked={joinedColumns.includes(c.id)} onChange={e=>setJoinedColumns(current=>e.target.checked?[...current,c.id]:current.filter(id=>id!==c.id))}/><span>{c.displayName||c.name}<small>{c.name} · {c.type}</small></span></label>)}{a&&eligible.length===0&&<span className="muted">Tidak ada kolom unik yang dapat ditambahkan.</span>}</div><label className="foreign-column-toggle"><input type="checkbox" checked={showForeignKey} onChange={e=>setShowForeignKey(e.target.checked)}/> Tampilkan kolom foreign key dari tabel tujuan pada hasil join</label></section>}
    <div className="info-box">{kind==='many-to-many'?'Tabel penghubung dengan composite primary key dan dua foreign key akan dibuat otomatis.':'Nama kolom sumber dan tujuan boleh berbeda, tetapi tipe data harus sama. Referensi harus menuju PK tunggal atau UNIQUE.'}</div>{error&&<div className="form-error" role="alert">{error}</div>}
  </div><footer className="modal-footer"><button onClick={onClose}>Batal</button><button className="primary" onClick={save}>{editing?'Simpan relasi':'Buat relasi'}</button></footer></section></div>;
}
