'use client';
import { useState } from 'react';
import { ArrowRight, X } from 'lucide-react';
import { connect, isReferenceKey, junction, Project, Relation } from '../lib/schema';
export default function RelationDialog({project,initial,onSave,onClose}: {project:Project;initial?:{fromTable:string;fromColumn:string;toTable:string;toColumn:string};onSave:(p:Project)=>void;onClose:()=>void}) {
  const [fromTable,setFromTable]=useState(initial?.fromTable||project.tables[0]?.id||'');
  const [toTable,setToTable]=useState(initial?.toTable||project.tables[1]?.id||project.tables[0]?.id||'');
  const a=project.tables.find(t=>t.id===fromTable), b=project.tables.find(t=>t.id===toTable);
  const [fromColumn,setFromColumn]=useState(initial?.fromColumn||a?.columns.find(c=>isReferenceKey(a,c))?.id||'');
  const [toColumn,setToColumn]=useState(initial?.toColumn||b?.columns.find(c=>!c.primaryKey)?.id||b?.columns[0]?.id||'');
  const [kind,setKind]=useState<Relation['kind']|'many-to-many'>('one-to-many'); const [error,setError]=useState('');
  function save(){try{if(!a||!b)throw new Error('Pilih kedua tabel.');onSave(kind==='many-to-many'?junction(project,a,b):connect(project,fromTable,fromColumn,toTable,toColumn,kind));}catch(e){setError((e as Error).message);}}
  return <div className="modal-backdrop"><section className="modal relation-modal" role="dialog" aria-modal="true" aria-labelledby="relation-title" onKeyDown={e=>{if(e.key==='Escape')onClose();}}><header className="modal-header"><div><span className="eyebrow">CONNECT YOUR DATA</span><h2 id="relation-title">Tambah relasi</h2></div><button className="icon-button" aria-label="Tutup relasi" onClick={onClose}><X size={20}/></button></header><div className="modal-body">
    <label>Jenis relasi<select autoFocus aria-label="Jenis relasi" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="one-to-many">One-to-many · 1 : N</option><option value="one-to-one">One-to-one · 1 : 1</option><option value="many-to-many">Many-to-many · N : N</option></select></label>
    <div className="relation-fields"><div><label>Tabel referensi (1)<select aria-label="Tabel referensi" value={fromTable} onChange={e=>{setFromTable(e.target.value);const t=project.tables.find(t=>t.id===e.target.value)!;setFromColumn(t.columns.find(c=>isReferenceKey(t,c))?.id||'');}}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<label>Kolom PK / UNIQUE<select aria-label="Kolom referensi" value={fromColumn} onChange={e=>setFromColumn(e.target.value)}><option value="">Pilih kolom</option>{a?.columns.filter(c=>isReferenceKey(a,c)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label>}</div><ArrowRight size={22}/><div><label>Tabel tujuan (FK)<select aria-label="Tabel tujuan" value={toTable} onChange={e=>{setToTable(e.target.value);const t=project.tables.find(t=>t.id===e.target.value)!;setToColumn(t.columns.find(c=>!c.primaryKey)?.id||t.columns[0].id);}}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<label>Kolom foreign key<select aria-label="Kolom tujuan" value={toColumn} onChange={e=>setToColumn(e.target.value)}>{b?.columns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label>}</div></div>
    <div className="info-box">{kind==='many-to-many'?'Tabel penghubung dengan composite primary key dan dua foreign key akan dibuat otomatis.':kind==='one-to-one'?'Kolom tujuan otomatis menjadi UNIQUE. Kedua kolom harus memiliki tipe data yang sama.':'Referensi harus menuju PK tunggal atau UNIQUE. Kedua kolom harus memiliki tipe data yang sama.'}</div>{error&&<div className="form-error" role="alert">{error}</div>}
  </div><footer className="modal-footer"><button onClick={onClose}>Batal</button><button className="primary" onClick={save}>Buat relasi</button></footer></section></div>;
}
