'use client';
import { useMemo, useState } from 'react';
import { ArrowRight, X } from 'lucide-react';
import { connect, isReferenceKey, junction, Project, Relation, validateProject } from '../lib/schema';
type Initial = Pick<Relation, 'id'|'fromTable'|'fromColumn'|'toTable'|'toColumn'|'kind'|'joinedColumns'|'showForeignKey'>;
export default function RelationDialog({project,initial,onSave,onClose}: {project:Project;initial?:Partial<Initial>;onSave:(p:Project)=>void;onClose:()=>void}) {
  const [fromTable,setFromTable]=useState(initial?.fromTable||project.tables[0]?.id||''); const [toTable,setToTable]=useState(initial?.toTable||project.tables[1]?.id||project.tables[0]?.id||'');
  const a=project.tables.find(t=>t.id===fromTable), b=project.tables.find(t=>t.id===toTable);
  const [fromColumn,setFromColumn]=useState(initial?.fromColumn||a?.columns.find(c=>isReferenceKey(a,c))?.id||''); const [toColumn,setToColumn]=useState(initial?.toColumn||b?.columns.find(c=>!c.primaryKey)?.id||b?.columns[0]?.id||'');
  const [kind,setKind]=useState<Relation['kind']|'many-to-many'>(initial?.kind||'one-to-many'); const [joinedColumns,setJoinedColumns]=useState<string[]>(initial?.joinedColumns||[]); const [showForeignKey,setShowForeignKey]=useState(initial?.showForeignKey??true); const [error,setError]=useState('');
  const eligible=useMemo(()=>a?.columns.filter(c=>!b?.columns.some(target=>target.name.toLowerCase()===c.name.toLowerCase()))||[],[a,b]);
  function save(){try{if(!a||!b)throw new Error('Pilih kedua tabel.');if(initial?.id){const next=structuredClone(project);const relation=next.relations.find(r=>r.id===initial.id);if(!relation)throw new Error('Relasi tidak ditemukan.');Object.assign(relation,{joinedColumns,showForeignKey});onSave(validateProject(next));}else onSave(kind==='many-to-many'?junction(project,a,b):connect(project,fromTable,fromColumn,toTable,toColumn,kind,{joinedColumns,showForeignKey}));}catch(e){setError((e as Error).message);}}
  return <div className="modal-backdrop"><section className="modal relation-modal" role="dialog" aria-modal="true" aria-labelledby="relation-title" onKeyDown={e=>{if(e.key==='Escape')onClose();}}><header className="modal-header"><div><span className="eyebrow">CONNECT YOUR DATA</span><h2 id="relation-title">{initial?'Atur hasil join':'Tambah relasi'}</h2></div><button className="icon-button" aria-label="Tutup relasi" onClick={onClose}><X size={20}/></button></header><div className="modal-body">
    {!initial&&<><label>Jenis relasi<select autoFocus aria-label="Jenis relasi" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="one-to-many">One-to-many · 1 : N</option><option value="one-to-one">One-to-one · 1 : 1</option><option value="many-to-many">Many-to-many · N : N</option></select></label><div className="relation-fields"><div><label>Tabel referensi (1)<select aria-label="Tabel referensi" value={fromTable} onChange={e=>{setFromTable(e.target.value);const t=project.tables.find(t=>t.id===e.target.value)!;setFromColumn(t.columns.find(c=>isReferenceKey(t,c))?.id||'');setJoinedColumns([]);}}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<label>Kolom PK / UNIQUE<select aria-label="Kolom referensi" value={fromColumn} onChange={e=>setFromColumn(e.target.value)}><option value="">Pilih kolom</option>{a?.columns.filter(c=>isReferenceKey(a,c)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label>}</div><ArrowRight size={22}/><div><label>Tabel tujuan (FK)<select aria-label="Tabel tujuan" value={toTable} onChange={e=>{setToTable(e.target.value);const t=project.tables.find(t=>t.id===e.target.value)!;setToColumn(t.columns.find(c=>!c.primaryKey)?.id||t.columns[0].id);setJoinedColumns([]);}}>{project.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{kind!=='many-to-many'&&<label>Kolom foreign key<select aria-label="Kolom tujuan" value={toColumn} onChange={e=>setToColumn(e.target.value)}>{b?.columns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label>}</div></div></>}
    {kind!=='many-to-many'&&<section className="join-settings"><h3>Kolom hasil join</h3><p>Pilih kolom dari tabel referensi yang ditampilkan pada hasil join. Kolom dengan nama yang sudah ada di tabel tujuan tidak dapat dipilih; nama kolom tidak diberi prefix.</p><div className="join-columns">{eligible.map(c=><label key={c.id}><input type="checkbox" checked={joinedColumns.includes(c.id)} onChange={e=>setJoinedColumns(current=>e.target.checked?[...current,c.id]:current.filter(id=>id!==c.id))}/><span>{c.displayName||c.name}<small>{c.name} · {c.type}</small></span></label>)}{a&&eligible.length===0&&<span className="muted">Tidak ada kolom unik yang dapat ditambahkan.</span>}</div><label className="foreign-column-toggle"><input type="checkbox" checked={showForeignKey} onChange={e=>setShowForeignKey(e.target.checked)}/> Tampilkan kolom foreign key dari tabel tujuan pada hasil join</label></section>}
    <div className="info-box">{kind==='many-to-many'?'Tabel penghubung dengan composite primary key dan dua foreign key akan dibuat otomatis.':kind==='one-to-one'?'Kolom tujuan otomatis menjadi UNIQUE. Kedua kolom harus memiliki tipe data yang sama.':'Referensi harus menuju PK tunggal atau UNIQUE. Kedua kolom harus memiliki tipe data yang sama.'}</div>{error&&<div className="form-error" role="alert">{error}</div>}
  </div><footer className="modal-footer"><button onClick={onClose}>Batal</button><button className="primary" onClick={save}>{initial?'Simpan pengaturan':'Buat relasi'}</button></footer></section></div>;
}
